### PR TITLE
Update swift tools version to 5.8

### PR DESCRIPTION
**Pull request by GNMoseke**
As of [queues 1.15](https://github.com/vapor/queues/releases/tag/1.15.0), swift 5.8 is required to build. This package is still on 5.6, and vapor itself is also on 5.8.

Also updates the README accordingly.

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
Thanks!

**Comment by GNMoseke** [comment]
Ah I did not think about CI - @0xTim do you have a preference on removing the 5.6/5.7 jobs altogether or bumping them up to 5.10?

**Comment by 0xTim** [comment]
@GNMoseke yeah just remove them and add jobs for 5.10 and 6.0

**Comment by gwynne** [comment]
I've updated the CI more comprehensively (there were several other things that needed to be addressed) in #42

**Comment by GNMoseke** [comment]
Thanks @gwynne!

**Pull request merged**
