### PR TITLE
Use Redis v4 release

### PR DESCRIPTION
**Pull request by Mordil**

### CODE REVIEW

**Review by jdmcd — APPROVED** [review]
LGTM, thanks!

**Comment by jdmcd** [comment]
@Mordil this was marked as a draft but it LGTM, is it ready on your end?

**Comment by Mordil** [comment]
@jdmcd That's because it's pointing to the branch `v4-release`. We don't want to merge this until Redis 4.0 is officially released and tagged. Once it is, I'll update this PR to point to that tag and then we can release QRD 1.0

See https://github.com/vapor/redis/pull/174

**Comment by Mordil** [comment]
Unless of course you disagree and think we can merge and do a pre-release tag and then just update to use the official 4.0 tag

It's up to you

**Comment by tanner0101** [comment]
These changes are now available in [1.0.0-rc.4.1](https://github.com/vapor/queues-redis-driver/releases/tag/1.0.0-rc.4.1)

**Pull request merged**
