### PR TITLE
Drop RedisKit dependency to use Vapor/Redis directly

### PR DESCRIPTION
**Pull request by Mordil**
Drop RedisKit and use Vapor/Redis directly (#19)

### CODE REVIEW

**Review by jdmcd — APPROVED** [review]
@Mordil thanks so much! I think this LGTM. Would like to get @tanner0101's eyes on it as well but I think it's great.

**Comment by kaishin** [comment]
Any chance this gets merged before the stable release of `vapor/redis`?

**Review by 0xTim — APPROVED** [review]
LGTM

**Comment by tanner0101** [comment]
These changes are now available in [1.0.0-rc.4](https://github.com/vapor/queues-redis-driver/releases/tag/1.0.0-rc.4)

**Pull request merged**
